name: podcast_analytics
version: "1.0"
config-version: 2
profile: podcast_analytics
model-paths: ["models"]
seed-paths: ["../seeds"]
models:
  podcast_analytics:
    1.staging:
      +materialized: view
    2.intermediate:
      +materialized: view
    3.marts:
      +materialized: table
