name: podcast_analytics
version: "1.0"
config-version: 2
profile: podcast_analytics
model-paths: ["models"]
seed-paths: ["../seeds"]
models:
  elementary:
    +schema: elementary
  podcast_analytics:
    1.staging:
      +materialized: view
    2.intermediate:
      +materialized: view
    3.marts:
      +materialized: table

# Required from dbt 1.8 and above for certain Elementary features
flags:
  require_explicit_package_overrides_for_builtin_materializations: False
  source_freshness_run_project_hooks: True
