version: 2

sources:
  - name: raw
    schema: public
    tables:
      - name: event_files
        identifier: raw_event_files
      - name: users
        identifier: raw_users
      - name: episodes
        identifier: raw_episodes

models:
  - name: stg_user_events
    description: "Typed raw event records"
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: event_type
        tests:
          - accepted_values:
              values: ["play", "pause", "seek", "complete"]

  - name: stg_user_events_invalid
    description: "Invalid event records for data quality investigation"
    columns:
      - name: issue_type
        tests:
          - accepted_values:
              values:
                [
                  "missing_event_type",
                  "invalid_event_type",
                  "missing_timestamp",
                  "malformed_timestamp",
                  "missing_user_id",
                  "missing_episode_id",
                  "other_issue",
                ]

  - name: stg_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null

  - name: stg_episodes
    columns:
      - name: episode_id
        tests:
          - unique
          - not_null
  - name: dim_episodes
    columns:
      - name: episode_id
        tests:
          - unique
          - not_null
      - name: title
        tests:
          - not_null
  - name: dim_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null

  - name: fact_user_events
    columns:
      - name: user_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_users')
              field: user_id
      - name: episode_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_episodes')
              field: episode_id
      - name: event_type
        tests:
          - accepted_values:
              values: ["play", "pause", "seek", "complete"]
