version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: podcast_pg
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
